name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # يشغل يوميًا
  workflow_dispatch: # يسمحلك تشغله يدويًا

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Ahmad-Alsabah
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "output/*.svg"
